# Generated by Django 2.0.3 on 2018-04-09 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profil',
            name='avatar',
            field=models.ImageField(blank=True, default='core/img/750x300.png', upload_to='core/img/upload/'),
        ),
    ]
