# Generated by Django 2.0.3 on 2018-04-11 15:01

from django.db import migrations
import markdownx.models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_profil_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profil',
            name='description',
            field=markdownx.models.MarkdownxField(blank=True, null=True),
        ),
    ]
