# Generated by Django 2.0.3 on 2018-04-27 15:19

from django.db import migrations, models
import markdownx.models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20180424_1747'),
    ]

    operations = [
        migrations.CreateModel(
            name='Parametres',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('a_propos_description', markdownx.models.MarkdownxField(verbose_name='description de la communautée')),
            ],
        ),
    ]
