# Generated by Django 2.0.3 on 2018-05-03 09:01

from django.db import migrations, models
import markdownx.models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20180424_1747'),
    ]

    operations = [
        migrations.CreateModel(
            name='Parametre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('valeur', markdownx.models.MarkdownxField(blank=True, null=True)),
            ],
        ),
    ]
