# Generated by Django 2.0.3 on 2018-04-27 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20180427_1731'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parametres',
            name='nom',
            field=models.CharField(max_length=50),
        ),
    ]
