# Generated by Django 2.0.3 on 2018-03-21 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='sousTitre',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
