# Generated by Django 2.0.3 on 2018-03-22 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='sousTitre',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
