# Generated by Django 2.0.3 on 2018-03-25 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20180322_2151'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='header',
            field=models.ImageField(blank=True, default='750x300.png', upload_to='upload/'),
        ),
        migrations.AlterField(
            model_name='article',
            name='sousTitre',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
