# Generated by Django 2.0.4 on 2018-04-06 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20180403_0925'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='header',
            field=models.ImageField(blank=True, default='blog/img/750x300.png', upload_to='blog/img/upload/'),
        ),
    ]
