# Generated by Django 2.0.3 on 2018-04-24 19:49

from django.db import migrations, models
import markdownx.models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20180424_2147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='auteur',
            field=models.CharField(max_length=42),
        ),
        migrations.AlterField(
            model_name='article',
            name='contenu',
            field=markdownx.models.MarkdownxField(),
        ),
    ]
